export default [
  "",
  {
    title: "CSS篇",
    collapsable: true,
    children: [
      "CSS篇/css选择器.md",
      "CSS篇/rem详解及使用方法.md",
      "CSS篇/CSS中规则@media的用法.md",
      "CSS篇/css3 transition 笔记.md",
      "CSS篇/垂直居中.md",
      "CSS篇/文本过长显示省略号的几种方式.md",
      "CSS篇/根据包含的子元素个数，实现不同的样式.md",
      "CSS篇/如何解决 float 元素浮动后高度不一致导致错位的问题.md",
      "CSS篇/在 less 中如何使用 CSS3 的 calc 属性.md",
      "CSS篇/Less篇-模拟for循环生成css.md",
    ],
  },
  {
    title: "webpack 完全教程",
    collapsable: true,
    children: [
      "webpack 完全教程/webpack 完全教程-01-介绍.md",
      "webpack 完全教程/webpack 完全教程-02-学习环境.md",
      "webpack 完全教程/webpack 完全教程-03-快速上手.md",
      "webpack 完全教程/webpack 完全教程-04-webpack 命令行说明.md",
      "webpack 完全教程/webpack 完全教程-05-webpack 集成 npm scripts.md",
      "webpack 完全教程/webpack 完全教程-06-编译css资源.md",
      "webpack 完全教程/webpack 完全教程-07-编译ES6代码.md",
      "webpack 完全教程/webpack 完全教程-08-使用UglifyJs Plugin压缩资源.md",
      "webpack 完全教程/webpack 完全教程-09-多入口文件编译.md",
      "webpack 完全教程/webpack 完全教程-10-devtool让源码在浏览器中可调试.md",
    ],
  },
  {
    title: "思考及感悟",
    collapsable: false,
    children: [
      "思考及感悟/前端性能优化（把2M的文件变为75K的过程）.md",
      "思考及感悟/HTTP 缓存策略.md",
      "思考及感悟/常见的web安全问题总结.md",
      "思考及感悟/如何区分基础组件和业务组件.md",
      "思考及感悟/flex 布局在移动端的兼容性问题.md",
      "思考及感悟/浏览器渲染原理及性能优化技巧与实践.md",
      "思考及感悟/移动前端性能优化的一些策略.md",
      "思考及感悟/跨平台开发方案.md",
      "思考及感悟/关于处理跨域问题的讨论.md",
      "思考及感悟/扫盲CRLF、CR、LF都是什么鬼？.md",
      "思考及感悟/对前端开发中组件、插件、控件的理解.md",
      "思考及感悟/更少，但更好.md",
      "思考及感悟/6月12-6月17日~工作思考篇.md",
      "思考及感悟/对日常开发的两点建议.md",
      "思考及感悟/下一步我们该怎么走.md",
      "思考及感悟/像写代码一样写文档，严谨！像写文档一样写代码，规范！.md",
      "思考及感悟/Vue3 Composition API 实战指南.md",
      "思考及感悟/TypeScript 在前端项目中的最佳实践.md",
      "思考及感悟/前端工程化之 CI-CD 实践.md",
      "思考及感悟/微前端架构设计与实现.md",
      "思考及感悟/WebAssembly 在前端性能优化中的应用.md",
      "思考及感悟/React Hooks 最佳实践.md",
      "思考及感悟/前端状态管理方案对比.md",
      "思考及感悟/前端性能监控与优化.md",
      "思考及感悟/前端安全防护实践.md",
      "思考及感悟/前端测试策略与实践.md",
      "思考及感悟/前端工程化之代码规范.md",
      "思考及感悟/前端工程化之项目结构设计.md",
      "思考及感悟/前端工程化之模块化开发.md",
      "思考及感悟/前端工程化之构建优化.md",
      "思考及感悟/前端工程化之部署策略.md",
    ],
  },
];
